--------------------------------------------requires------------------------------------------------

local term = require("term")
local text = require("text")
local com = require('component')
local gpu = com.gpu
local shell = require("shell")
local thread = require("thread")

----------------------------------------------------------------------------------------------------

term.clear()
local width, height = gpu.getResolution()
local text = [[MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmmm:              :mmmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhh+                            +hhhhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMyyy/                                      /yyyMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMmooo`                                            `ooomMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMM+:                  /ssssssssssssss/                  :++yMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNh:::           ````ohhhhNMMMMMMMMMMMMMMNhhhho````            `:hNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNm-.          ```yddddNMMMMMMMMMMMMMMMMMMMMMMMMNddddy```          .-mNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMNm/.          .:mmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmm:..`        ./mNMMMMMMMMMMMMM
MMMMMMMMMMMMdo`        `---mNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNy-`        `odMMMMMMMMMMMM
MMMMMMMMMMhs          :oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo:          shMMMMMMMMMM
MMMMMMMMMM.         :+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+:         `sdMMMMMMMM
MMMMMMMMh+`       -smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms-         oMMMMMMMM
MMMMMMm/.        ydMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdy        ./mMMMMMM
MMMMMMd         `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM`         dMMMMMM
MMMMM:.``     `hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh`       `.MMMMM
MMMmdhhh+--. +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+      .:MMMMM
MMM+````/yys:sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs:``:::syhmMMM
MMM/       .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy:    :yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++sss.  +MMM
Mmo-       .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd        dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm      -omM
Mh        oyMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+:        :+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm        hM
Mh        mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM`   ```    `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm        yN
Ny      ``mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNN`  +ddy``  `NNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm``      .-
.`      +mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+.   sMMMmo   .+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+        
        oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/  `-yMMMMy-`  :dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo        
        oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy:  -MMMMMMMM-    yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo        
        oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs/    -MMMMMMMM-    yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo        
        oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM     oyMMMMMMMMyo   :+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo        
        oMMMMMMMMMMMMMMMMMMMMMMMMMMMMo:     NMMMMMMMMMMN     MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo        
        oMMMMMMMMMMMMMMMMMMMMMMMMMMMM:      ------------     NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo        
.`      +mMMMMMMMMMMMMMMMMMMMMMMMMMMM:                       ./MMMMMMMMMMMMMMMMMMMMMMMMMMMm+        
Ny      ``mMMMMMMMMMMMMMMMMMMMMMMMMNd-    .--------------.    -dNMMMMMMMMMMMMMMMMMMMMMMMMm``      .-
Mh        mMMMMMMMMMMMMMMMMMMMMMMMMy`   `:hNNNNNNNNNNNNNNh:`   `yMMMMMMMMMMMMMMMMMMMMMMMMm        yN
Mh        oyMMMMMMMMMMMMMMMMMMMMMMMs    /MMMMMMMMMMMMMMMMMM/    /yNMMMMMMMMMMMMMMMMMMMMMMm        hM
Mmo-       .MMMMMMMMMMMMMMMMMMMMMNo:    /MMMMMMMMMMMMMMMMMM/      NMMMMMMMMMMMMMMMMMMMMMs+        hM
MMM/       .MMMMMMMMMMMMMMMMMMMMMN    `yhMMMMMMMMMMMMMMMMMMhy`    NMMMMMMMMMMMMMMMMMMMMM.       -ymM
MMM+`      `:sMMMMMMMMMMMMMMMMMMMMhhhhhMMMMMMMMMMMMMMMMMMMMMMhhhhhMMMMMMMMMMMMMMMMMMMMy/``     `+MMM
MMMmd`       +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhhy``` `dmMMM
MMMMM.`   ```+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd````-ddd:.MMMMM
MMMMMMm---hdd+ sdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMds        dMMMMMM
MMMMMMMMdy.      ydMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdy        ./mMMMMMM
MMMMMMMMo         -smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms-         oMMMMMMMM
MMMMMMMMds`         :+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+:         `sdMMMMMMMM
MMMMMMMMMMhs          :oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo:          shMMMMMMMMMM
MMMMMMMMMMMMdo`        `---mNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNy-`        `odMMMMMMMMMMMM
MMMMMMMMMMMMMNm/.          .:mmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmm:..`        ./mNMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNm-.          ```yddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMmddy```          .-mNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNh:`            ``:hhhhhhNMMMMMMMMMMMMMMNhhhhhh:``            `:hNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMy++:                  /ssssssssssssss/                  :++yMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMmooo`                                            `ooomMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMyyy/                                      /yyyMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhh+                              yhhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmms                  smmmmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]]

gpu.set(width / 2 - #text / 2, height / 2, text)
shell.execute("/UntitledOS/System/sys-start.lua")
