term.clear()
term.setCursorPos(1,1)
shell.run("bg /AntwitchOS/System/Systemstart")
print("Starting Computer...")
for i = 1, math.random(1,10) do
    term.setCursorPos(1,2)
    print("-")
    sleep(0.1)
    term.setCursorPos(1,2)
    print("--")
    sleep(0.1)
    term.setCursorPos(1,2)
    print("---")
    sleep(0.1)
    term.setCursorPos(1,2)
    print("----")
    sleep(0.1)
    term.setCursorPos(1,2)
    print(" ----")
    sleep(0.1)
    term.setCursorPos(1,2)
    print("  ----")
    sleep(0.1)
    term.setCursorPos(1,2)
    print("   ----")
    sleep(0.1)
    term.setCursorPos(1,2)
    print("    ----")
    sleep(0.1)
    term.setCursorPos(1,2)
    print("     ----")
    sleep(0.1)
    term.setCursorPos(1,2)
    print("       ---")
    sleep(0.1)
    term.setCursorPos(1,2)
    print("         --")
    sleep(0.1)
    term.setCursorPos(1,2)
    print("           -")
    sleep(0.1)
    term.setCursorPos(1,2)
    print("             ")
    sleep(0.1)
    term.setCursorPos(1,2)
    print("-")
    sleep(0.05)
    term.setCursorPos(1,2)
    print("--")
    sleep(0.05)
    term.setCursorPos(1,2)
    print("---")
    sleep(0.05)
    term.setCursorPos(1,2)
    print("----")
    sleep(0.05)
    term.setCursorPos(1,2)
    print(" ----")
    sleep(0.05)
    term.setCursorPos(1,2)
    print("  ----")
    sleep(0.05)
    term.setCursorPos(1,2)
    print("   ----")
    sleep(0.05)
    term.setCursorPos(1,2)
    print("    ----")
    sleep(0.05)
    term.setCursorPos(1,2)
    print("     ----")
    sleep(0.05)
    term.setCursorPos(1,2)
    print("       ---")
    sleep(0.05)
    term.setCursorPos(1,2)
    print("         --")
    sleep(0.05)
    term.setCursorPos(1,2)
    print("           -")
    sleep(0.05)
    term.setCursorPos(1,2)
    print("             ")
end



shell.run("/AntwitchOS/desktop.lua")
sleep(3)
os.shutdown()
