sh = require("shell")
co = require("computer")
sh.execute("pastebin run ryhyXUKZ")
sh.execute("wget -f https://raw.githubusercontent.com/kazu55/testos/master/lib/core/boot.lua /lib/core/boot.lua")
co.shutdown(true)
